version: "3.8"

services:
  web:
    image: medids0526/friendlyhello:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=80"

  compa:
    image: ritatrcr/friendlyhello:latest
    platform: linux/arm64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.compa.rule=Host(`compa.localhost`)"
      - "traefik.http.routers.compa.entrypoints=web"
      - "traefik.http.services.compa.loadbalancer.server.port=80"

  redis:
    image: redis
    volumes:
      - "./data:/data"
    command: redis-server --appendonly yes
    labels:
      - "traefik.enable=false"

  traefik:
    image: traefik:v2.3
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:4000"
    ports:
      - "4000:4000"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
